"""add is_author col inplace archived col

Revision ID: 2d9abdb3ceb6
Revises: 0cc160c145e6
Create Date: 2023-02-11 15:17:12.491290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9abdb3ceb6'
down_revision = '0cc160c145e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_author', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.drop_column('archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_column('is_author')

    # ### end Alembic commands ###
