"""del is_author

Revision ID: 6192a7460c0a
Revises: b37b1039fcf7
Create Date: 2023-02-11 21:16:42.256500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6192a7460c0a'
down_revision = 'b37b1039fcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_author', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
